### ISSUE TITLE
DiffBind: package or namespace load failed for ‘GenomeInfoDb’

### ISSUE THREAD

**Issue by bwassie** [galaxyproject/tools-iuc#1824]
I've been using the updated DiffBind tool with collections for case and control and I've been getting this error:

`Error: package or namespace load failed for ‘GenomeInfoDb’ in loadNamespace(i, c(lib.loc, .libPaths()), versionCheck = vI[[i]]):
 there is no package called ‘GenomeInfoDbData’
Error: package ‘GenomeInfoDb’ could not be loaded`

If I was working on a local version of DiffBind I would try installing the package in R but I'm not sure what to do in this case. Any help is appreciated!

**Comment by mblue9** [comment]
That sounds like diffbind didn't install properly. Are you running it in a local instance?

I just tested it in usegalaxy.eu and it seems to be working fine there, see this history here: https://galaxy.uni-freiburg.de/u/mblue9/h/testing-diffbind

**Comment by zfrenchee** [comment]
@mblue9 we're working out of a dockerized galaxy. 

Which diffbind is the appropriate one? When I go to the test tool shed, I see

Name↓ | Synopsis | Type | Installable Revisions | Owner
-- | -- | -- | -- | --
diffbind | Diffbind provides functions for processing ChIP-Seq data. | Unrestricted | 23 (2018-04-07) | bgruening
diffbind | Diffbind provides functions for processing ChIP-Seq data. | Unrestricted | 0 (2018-03-20) | iuc

I would assume the second one is correct, since diffbind was migrated to tools-iuc, but maybe @bgruening is still deploying to the tool shed, which means his name is attached? 

In the main toolshed, all I see is: 

Name↓ | Synopsis | Type | Installable Revisions | Owner
-- | -- | -- | -- | --
diffbind | Diffbind provides functions for processing ChIP-Seq data. | Unrestricted | 11 (2018-04-07) | bgruening

I believe the version @bwassie tested is this last one, which had the error with `GenomeInfoDb`.

**Comment by zfrenchee** [comment]
Oh, and @mblue9, for the history you shared, I'm logged in to galaxy.eu, but not able to access the datasets:

<img width="867" alt="screen shot 2018-04-11 at 10 43 02 am" src="https://user-images.githubusercontent.com/2761597/38624126-517b6c2a-3d75-11e8-9525-fd27112883f5.png">

**Comment by mblue9** [comment]
It's the version in the main toolshed, the last one you've listed above. It has bgruening as Owner and not iuc because the tool lineage keeps the original owner. But I don't know why there's an iuc one in test toolshed (ping @bgruening) 

Did you install diffbind into the Galaxy you've got or did it come already installed? 
Are you able to uninstall and reinstall? As that version is working fine in usegalaxy.eu

I've published that history now instead of sharing it can you try importing again? 

(@jennaj how do you share a history link without getting those grey padlocks?)

**Comment by zfrenchee** [comment]
@mblue9 I've tried uninstall/reinstall, with the same error. When the package installs, I see

<img width="1039" alt="screen shot 2018-04-11 at 10 46 26 am" src="https://user-images.githubusercontent.com/2761597/38643498-480a2510-3dab-11e8-90f0-e6ed39f39bb4.png">

(I don't see GenomeInfoDb but that might not mean anything). 

I'm still seeing the padlocks unfortunately https://galaxy.uni-freiburg.de/u/mblue9/h/testing-diffbind

**Comment by bgruening** [comment]
I don't know about the test toolshed, probably a mistake. What counts is the TS :)

**Comment by zfrenchee** [comment]
The TS version of the tool is still failing for us with the same error, @bgruening.

**Comment by mblue9** [comment]
@zfrenchee I can only confirm that that version of diffbind from the TS (dated 2018-04-07) works fine for us in 17.09, but we're not using Docker. What image are you using and what version of Galaxy?

And does anyone know how we can get rid of those padlocks?

**Comment by zfrenchee** [comment]
@mblue9 I'm using a slight variant of @bgruening 's 18.01 image.

**Comment by zfrenchee** [comment]
I see this: 
```
root@720c6ed86163:/export/tool_deps/_conda/envs/mulled-v1-3ee81659f121f9d09d794944023d0d947163ed82e32e86c8c7ebc17b66b65bb2/conda-meta# ls
bioconductor-annotate-1.56.0-r3.4.1_0.json           bioconductor-rtracklayer-1.38.0-r3.4.1_0.json          libxcb-1.13-0.json                r-data.table-1.10.4-r3.4.1_0.json     r-knitr-1.20-r3.4.1_0.json                 r-rjson-0.2.15-r3.4.1_0.json
bioconductor-annotationdbi-1.40.0-r3.4.1_0.json      bioconductor-s4vectors-0.16.0-r3.4.1_0.json            libxml2-2.9.8-0.json              r-dbi-0.8-r3.4.1_0.json               r-labeling-0.3-r3.4.1_0.json               r-rlang-0.2.0-r3.4.1_0.json
bioconductor-annotationforge-1.20.0-r3.4.1_0.json    bioconductor-shortread-1.36.0-r3.4.1_0.json            ncurses-5.9-10.json               r-dichromat-2.0_0-r3.4.1_0.json       r-lambda.r-1.2-r3.4.1_0.json               r-rpart-4.1_13-r3.4.1_0.json
bioconductor-biobase-2.38.0-r3.4.1_0.json            bioconductor-summarizedexperiment-1.8.0-r3.4.1_0.json  openssl-1.0.2n-0.json             r-digest-0.6.12-r3.4.1_0.json         r-lattice-0.20_34-r3.4.1_0.json            r-rsqlite-2.0-r3.4.1_0.json
bioconductor-biocgenerics-0.24.0-r3.4.1_0.json       bioconductor-systempiper-1.12.0-r3.4.1_0.json          pango-1.40.14-0.json              r-dplyr-0.7.4-r3.4.1_0.json           r-latticeextra-0.6_28-r3.4.1_0.json        r-scales-0.5.0-r3.4.1_0.json
bioconductor-biocparallel-1.12.0-r3.4.1_0.json       bioconductor-tximport-1.6.0-r3.4.1_0.json              pcre-8.39-0.json                  readline-7.0-0.json                   r-lazyeval-0.2.1-r3.4.1_0.json             r-sendmailr-1.2_1-r3.4.1_0.json
bioconductor-biomart-2.34.2-r3.4.1_0.json            bioconductor-variantannotation-1.24.1-r3.4.1_0.json    pixman-0.34.0-1.json              r-evaluate-0.10.1-r3.4.1_0.json       r-locfit-1.5_9.1-r3.4.1_0.json             r-snow-0.4_2-r3.4.1_0.json
bioconductor-biostrings-2.46.0-r3.4.1_0.json         bioconductor-xvector-0.18.0-r3.4.1_0.json              r-acepack-1.4.1-r3.4.1_0.json     r-fail-1.3-r3.4.1_0.json              r-magrittr-1.5-r3.4.1_0.json               r-stringi-1.1.6-r3.4.1_0.json
bioconductor-bsgenome-1.46.0-r3.4.1_0.json           bioconductor-zlibbioc-1.24.0-r3.4.1_0.json             r-amap-0.8_14-r3.4.1_0.json       r-foreign-0.8_67-r3.4.1_0.json        r-markdown-0.8-r3.4.1_1.json               r-stringr-1.3.0-r3.4.1_0.json
bioconductor-category-2.44.0-r3.4.1_0.json           bzip2-1.0.6-1.json                                     r-assertthat-0.2.0-r3.4.1_0.json  r-formula-1.2_1-r3.4.1_0.json         r-mass-7.3_48-r3.4.1_0.json                r-survival-2.40_1-r3.4.1_0.json
bioconductor-delayedarray-0.4.1-r3.4.1_0.json        ca-certificates-2018.1.18-0.json                       r-backports-1.1.2-r3.4.1_0.json   r-futile.logger-1.4.3-r3.4.1_0.json   r-matrix-1.2_12-r3.4.1_0.json              r-tibble-1.4.2-r3.4.1_0.json
bioconductor-deseq2-1.18.1-r3.4.1_1.json             cairo-1.14.10-0.json                                   r-base-3.4.1-3.json               r-futile.options-1.0.0-r3.4.1_0.json  r-matrixstats-0.52.2-r3.4.1_0.json         r-utf8-1.1.3-r3.4.1_0.json
bioconductor-diffbind-2.6.6-r3.4.1_0.json            curl-7.59.0-1.json                                     r-base64enc-0.1_3-r3.4.1_0.json   r-gdata-2.18.0-r3.4.1_0.json          r-memoise-1.1.0-r3.4.1_0.json              r-viridis-0.4.0-r3.4.1_0.json
bioconductor-edger-3.20.7-r3.4.1_0.json              fontconfig-2.12.6-0.json                               r-batchjobs-1.6-r3.4.1_0.json     r-getopt-1.20.0-r3.4.1_0.json         r-mime-0.5-r3.4.1_0.json                   r-viridislite-0.2.0-r3.4.1_0.json
bioconductor-genefilter-1.60.0-r3.4.1_0.json         freetype-2.8.1-0.json                                  r-bbmisc-1.11-r3.4.1_0.json       r-ggplot2-2.2.1-r3.4.1_0.json         r-munsell-0.4.3-r3.4.1_0.json              r-xml-3.98_1.6-r3.4.1_0.json
bioconductor-geneplotter-1.56.0-r3.4.1_0.json        gettext-0.19.8.1-0.json                                r-bh-1.66.0_1-r3.4.1_0.json       r-ggrepel-0.7.0-r3.4.1_0.json         r-nnet-7.3_12-r3.4.1_0.json                r-xtable-1.8_2-r3.4.1_0.json
bioconductor-genomeinfodb-1.14.0-r3.4.1_0.json       glib-2.55.0-0.json                                     r-bindr-0.1.1-r3.4.1_0.json       r-glue-1.2.0-r3.4.1_0.json            r-openssl-1.0.1-r3.4.1_0.json              r-yaml-2.1.14-r3.4.1_0.json
bioconductor-genomeinfodbdata-1.0.0-r3.4.1_1.json    graphite2-1.3.11-0.json                                r-bindrcpp-0.2-r3.4.1_0.json      r-gplots-3.0.1-r3.4.1_0.json          r-pheatmap-1.0.8-r3.4.1_0.json             tk-8.6.7-0.json
bioconductor-genomicalignments-1.14.1-r3.4.1_0.json  gsl-2.1-2.json                                         r-bit-1.1_12-r3.4.1_0.json        r-gridextra-2.3-r3.4.1_0.json         r-pillar-1.2.1-r3.4.1_0.json               wget-1.18-0.json
bioconductor-genomicfeatures-1.28.5-r3.4.1_0.json    harfbuzz-1.7.6-0.json                                  r-bit64-0.9_5-r3.4.1_0.json       r-gtable-0.2.0-r3.4.1_0.json          r-pkgconfig-2.0.1-r3.4.1_0.json            xorg-kbproto-1.0.7-1.json
bioconductor-genomicranges-1.30.3-r3.4.1_0.json      history                                                r-bitops-1.0_6-r3.4.1_0.json      r-gtools-3.5.0-r3.4.1_0.json          r-plogr-0.1_1-r3.4.1_0.json                xorg-libx11-1.6.5-0.json
bioconductor-go.db-3.5.0-r3.4.1_1.json               icu-58.2-0.json                                        r-blob-1.1.1-r3.4.1_0.json        r-highr-0.6-r3.4.1_0.json             r-plyr-1.8.4-r3.4.1_0.json                 xorg-libxau-1.0.8-3.json
bioconductor-gostats-2.44.0-r3.4.1_0.json            jpeg-9b-2.json                                         r-brew-1.0_6-r3.4.1_0.json        r-hmisc-4.0_3-r3.4.1_0.json           r-prettyunits-1.0.2-r3.4.1_0.json          xorg-libxdmcp-1.1.2-3.json
bioconductor-graph-1.56.0-r3.4.1_0.json              krb5-1.14.6-0.json                                     r-catools-1.17.1-r3.4.1_0.json    r-htmltable-1.9-r3.4.1_0.json         r-progress-1.1.2-r3.4.1_0.json             xorg-libxrender-0.9.10-0.json
bioconductor-gseabase-1.40.0-r3.4.1_0.json           libffi-3.2.1-3.json                                    r-checkmate-1.8.2-r3.4.1_0.json   r-htmltools-0.3.6-r3.4.1_0.json       r-r6-2.2.2-r3.4.1_0.json                   xorg-renderproto-0.11.1-1.json
bioconductor-iranges-2.12.0-r3.4.1_0.json            libgcc-5.2.0-0.json                                    r-cli-1.0.0-r3.4.1_0.json         r-htmlwidgets-1.0-r3.4.1_0.json       r-rcolorbrewer-1.1_2-r3.4.1_0.json         xorg-xproto-7.0.31-6.json
bioconductor-limma-3.34.6-r3.4.1_0.json              libiconv-1.15-0.json                                   r-cluster-2.0.6-r3.4.1_0.json     r-httr-1.3.1-r3.4.1_0.json            r-rcpp-0.12.15-r3.4.1_0.json               xz-5.2.3-0.json
bioconductor-rbgl-1.54.0-r3.4.1_0.json               libpng-1.6.34-0.json                                   r-colorspace-1.3_2-r3.4.1_0.json  r-hwriter-1.3.2-r3.4.1_0.json         r-rcpparmadillo-0.7.800.2.0-r3.4.1_0.json  zlib-1.2.11-0.json
bioconductor-rgraphviz-2.22.0-r3.4.1_0.json          libssh2-1.8.0-2.json                                   r-crayon-1.3.4-r3.4.1_0.json      r-jsonlite-1.5-r3.4.1_0.json          r-rcurl-1.95_4.8-r3.4.1_0.json
bioconductor-rsamtools-1.30.0-r3.4.1_0.json          libtiff-4.0.9-0.json                                   r-curl-3.2-r3.4.1_0.json          r-kernsmooth-2.23_15-r3.4.1_0.json    r-reshape2-1.4.3-r3.4.1_0.json
```

**Comment by mblue9** [comment]
Hmm I guess it could maybe be a (Docker?) setup issue, see a similarish-sounding issue here, to do with the file path https://support.bioconductor.org/p/97913/

But a couple of questions:

-  Are you able to load diffbind within that env without getting the genomeinfo db error? e.g. if you activate the env:
 
`source ~/miniconda3/bin/activate /Users/maria/miniconda3/envs/mulled-v1-3ee81659f121f9d09d794944023d0d947163ed82e32e86c8c7ebc17b66b65bb2/`
 
then start up R and try to load in Diffbind with `library(DiffBind)` does it load ok?

- Are you able to install and run other R tools like deseq2?

**Comment by bgruening** [comment]
It seem to work for me. I just installed it in ngs-preprocessing:18.01 and install it. @zfrenchee can you confirm it works with this Docker container?

**Comment by zfrenchee** [comment]
@mblue9 also getting the same error with DESeq2 (this started with upgrade to @bgruening's 18.01 image). Seems like this isn't a diffbind-specific issue, so I'll close.

**Comment by mblue9** [comment]
Ok cool, I hope you get your instance working!
